# Generated by Django 4.1.1 on 2023-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.IntegerField()),
                ('success', models.BooleanField()),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
